#!/usr/bin/env python3
"""Bind only official Play launchers/hooks to this project's working runtimes."""
from datetime import datetime, timezone
import json
from pathlib import Path
import shlex
import shutil

ROOT = Path(__file__).resolve().parent
USER_DIR = Path.home()
BUNDLE = USER_DIR / ".local/share/modiqo/play/skill/scripts/bin"
PYTHON = ROOT / ".play-venv/bin/python3"
assert PYTHON.is_file()
backup = ROOT / ".play-bootstrap" / ("scoped-launchers-" + datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ"))
backup.mkdir(parents=True, exist_ok=False)

changed = []
for name in ("play", "play-journey", "play-machine", "play-routing"):
    target = USER_DIR / ".local/bin" / name
    script = BUNDLE / name
    original = '#!/bin/sh\nexec "' + str(script) + '" "$@"\n'
    updated = "\n".join([
        "#!/bin/sh",
        "# Hackathon Play runtime binding; generated by configure-play-launchers.py.",
        "set -eu",
        "export ROTE_HOME=" + shlex.quote(str(ROOT / ".runtime")),
        "export PATH=" + shlex.quote(str(ROOT / ".play-venv/bin") + ":" + str(ROOT) + ":" + str(USER_DIR / ".local/bin")) + ':"$PATH"',
        "exec " + shlex.quote(str(PYTHON)) + " " + shlex.quote(str(script)) + ' "$@"',
        "",
    ])
    current = target.read_text()
    if current == updated:
        continue
    if current != original:
        raise SystemExit("Refusing to overwrite an unexpected Play launcher: " + str(target))
    shutil.copy2(target, backup / name)
    target.write_text(updated)
    target.chmod(0o755)
    changed.append(str(target))

hooks_file = USER_DIR / ".codex/hooks.json"
data = json.loads(hooks_file.read_text())
old_command = str(BUNDLE / "play-intercept") + " prompt 2>/dev/null || true"
new_command = shlex.quote(str(ROOT / "play-hook")) + " prompt 2>/dev/null || true"
found = False
for groups in data.get("hooks", {}).values():
    if not isinstance(groups, list):
        continue
    for group in groups:
        for hook in group.get("hooks", []):
            if hook.get("command") == new_command:
                found = True
            elif hook.get("command") == old_command:
                hook["command"] = new_command
                found = True
                changed.append(str(hooks_file))
if not found:
    raise SystemExit("Expected official Play prompt hook was not found; no hook was overwritten.")
if str(hooks_file) in changed:
    shutil.copy2(hooks_file, backup / "hooks.json")
    hooks_file.write_text(json.dumps(data, indent=2) + "\n")

receipt = {"changed": changed, "backup": str(backup), "python": str(PYTHON), "rote_home": str(ROOT / ".runtime")}
(ROOT / "reports/play-launcher-binding.json").write_text(json.dumps(receipt, indent=2) + "\n")
print("Configured %d Play-only launchers/hook entries; backup: %s" % (len(changed), backup))
